config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"

  resources :users, only: [:show]
  resources :events do
    resources :attendances, only: [:create, :destroy]
  end


  # resources :users, only: [:show] do
  #   resources :events, only: [:index, :new, :create]
  # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :attended_event, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User", foreign_key: "creator_id"
  has_many :attendances, foreign_key: "attended_event_id", inverse_of: 'attended_event', dependent: :destroy
  has_many :attendees, through: :attendances, dependent: :destroy

  scope :past, -> { where(event_datetime: ..(Time.now)) }
  scope :upcoming, -> { where(event_datetime: (Time.now)..) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :created_events, class_name: "Event", foreign_key: "creator_id", inverse_of: 'creator'
  has_many :attendances, foreign_key: "attendee_id", inverse_of: 'attendee'
  has_many :attended_events, through: :attendances

  def attending?(event)
    attendances.exists?(attended_event: event)
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:email, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def new
    @attendance = Attendance.new
  end

  def create
    @attendance = current_user.attendances.build(attendance_params)
    if @attendance.save
      redirect_to events_path, :notice => 'You are now attending the event.'
    else
      flash[:error] = 'Failed to attend the event.'
      redirect_to event_path(id: attendance_params.value)
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id])
    @attendance.destroy

    redirect_to root_path, :notice => 'You have left the event.'
  end

  private

  def attendance_params
    params.require(:attendance).permit(:attended_event_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_creator, only: [:new, :create]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @attendance = @event.attendances.build
  end

  def new
    @event = @creator.created_events.build
  end

  def create
    @event = @creator.created_events.build(event_params)

    if @event.save
      redirect_to event_path(@event)
    else
      flash.now[:error] = "Fix your Event!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path
  end

  private

  # def set_attandees
  #   @attendees
  # end

  def set_creator
    @creator = User.find(current_user.id)
  end

  def event_params
    params.require(:event).permit(:name, :event_datetime, :location, :creator_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/_form.html.erb
<%= form_with model: @attendance, url: event_attendances_path(@event[:id]), method: 'post' do |f| %>
  <%= f.hidden_field :attended_event_id, value: @event[:id]  %>
  <%= f.submit 'Attend Event' %>
<% end %>

app/views/events/edit.html.erb
<%= form_with model: @event do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li style="color: red"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Event:' %><br>
  <%= f.text_field :name %><br>
  <%= f.select :location, ["Mecca", "Medina"] %><br>
  <%= f.datetime_local_field :event_datetime %><br>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/events/index.html.erb
<h1>Events</h1>

<ul>
  <h2>Upcoming:</h2>
  <% @events.upcoming.each do |event| %>
      <li>
        <%= link_to "#{event.name}", event_path(event.id) %>
      </li>
  <% end %>
  <h2>Past:</h2>
  <% @events.past.each do |event| %>
      <li>
        <%= link_to "#{event.name}", event_path(event.id) %>
      </li>
  <% end %>
</ul>

<%= link_to "New Event", new_event_path %>

app/views/events/new.html.erb
<%= form_with model: @event do |f| %>

  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
          <li style="color: red"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label 'Event:' %><br>
  <%= f.text_field :name %><br>
  <%= f.select :location, ["Mecca", "Medina"] %><br>
  <%= f.datetime_local_field :event_datetime %><br>
  <%= f.hidden_field :creator_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1><%= @event.name %></h1>

<p>Location: <%= @event.location %></p>
<p>Location: <%= @event.event_datetime.strftime("%Y-%m-%d") %></p>

<h2> Attendees </h2>

<% @event.attendees.each do |person| %>
  <li>
    <%= person.name %>
  </li>
<%end%><br>

<% if user_signed_in? && !current_user.attending?(@event[:id]) %>

  <%= render 'attendances/form' %>

<% elsif user_signed_in? && current_user.attending?(@event[:id]) %>

  <%= form_with model: @attendance, url: event_attendance_path(@event[:id], @event.attendance_ids), method: 'delete' do |f| %>
      <%= f.hidden_field :id, value: @attendance.attended_event.id %>
      <%= f.submit 'Leave Event' %>
  <% end %>

<% end %><br>

<%= link_to "Delete Event", event_path(@event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?" } %>

<%= link_to "Edit Event", edit_event_path %>

<%= link_to "Events", events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
      <%= link_to "Profile", edit_user_registration_path %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <%= link_to "View Profile", user_path(current_user)%>
    <% else %>
      <%= link_to "Login", new_user_session_path %>
      <%= link_to "Sign Up", new_user_registration_path %>
    <% end %>

    
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>

<h2>Created Events:</h2>
<% if @created_events.any? %>
  <ul>
    <% @created_events.each do |event| %>
      <li><%= link_to "#{event.name}", event_path(event.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No events created yet.</p>
<% end %>

<h2>Attending Events:</h2>
<% if @user.attendances.any? %>
  <ul>
    <% @user.attended_events.where(event_datetime: (Time.now)..).each do |event| %>
      <li><%= link_to "#{event.name}", event_path(event.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>Not attending any events yet.</p>
<% end %>

<h2>Attended Events:</h2>
<% if @user.attendances.any? %>
  <ul>
    <% @user.attended_events.where(event_datetime: ..(Time.now)).each do |event| %>
      <li><%= link_to "#{event.name}", event_path(event.id) %></li>
    <% end %>
  </ul>
<% else %>
  <p>No past events attended.</p>
<% end %>

<%= link_to "Events", events_path %>